### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by eugene274** [rybalkinsd/atom#15]
![cpu_utilization](https://cloud.githubusercontent.com/assets/23106384/20643119/3f689694-b431-11e6-9293-70e8282fdbc7.png)

Problem caused by:
>while (true) {
>        ApplicationContext.instance().get(MessageSystem.class).execForService(this);
>}

in AccountService & ClientConnectionService

**Comment by eugene274** [comment]
#16

**Comment by rybalkinsd** [comment]
Merged
