### ISSUE TITLE
[Frontend] Подключение к вебсокету и отображение "Loading..."

### ISSUE THREAD

**Issue by elBroom** [rybalkinsd/atom#468]
1. В момент открытия страницы с игрой нужно открывался веб сокет коннект, без нажатия на канвас. 

2. Пока не пришло первое сообщение от сервера (`POSSESS`/`первая реплика`), канвас должен отображать "Loading..." и быть чёрным.

3. Сделать траву фоном, а не тайлами. (by @gammaker )

**Comment by gammaker** [comment]
1) Зачем? Вроде и так не мешает.
2) Лучше ждать не POSSESS, а первой реплики. У меня например POSSESS отсылается сразу при коннекте каждого игрока.

 Ещё предлагаю сделать траву фоном, а не тайлами. Пусть клиент отвечает за отрисовку травы, а сервер ничего о ней не должен знать.

**Comment by elBroom** [comment]
> Зачем? Вроде и так не мешает.
Получается одно лишнее движение на открытие сокета, когда это можно сделать автоматически. Раз пришел на страницу с игрой, играй, а так получается что все ждут.
> Лучше ждать не POSSESS, а первой реплики.

**Comment by rybalkinsd** [comment]
@gammaker @elBroom Траву на фон можно отдельной задачей делать, можно даже без меня

**Comment by SergDob** [comment]
Фронтенд не может обработать реплику, и, соответственно, ничего не отображает. В консоли браузера пишет ошибку:
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.handleReplica [as REPLICA] (Message.js:36)
    at WebSocket.socket.onmessage (ServerProxy.js:55)
и жалуется на строчку 36 в Message.js: 
    for (var i = 0; i < gameObjects.length; i++) {

В логах сервера все ОК, принимает сообщения:

[INFO ] 2017-05-16 17:53:10.498 [qtp1512981843-36] Broker - RECEIVED: {"topic":"MOVE","data":{"direction":"DOWN"}}
[INFO ] 2017-05-16 17:53:10.498 [qtp1512981843-36] EventServer - Received TEXT message: {"topic":"MOVE","data":{"direction":"DOWN"}}
[INFO ] 2017-05-16 17:53:10.498 [qtp1512981843-36] Broker - RECEIVED: {"topic":"MOVE","data":{"direction":"LEFT"}}
[INFO ] 2017-05-16 17:53:10.499 [qtp1512981843-36] EventServer - Received TEXT message: {"topic":"MOVE","data":{"direction":"LEFT"}}
